# A sample Gemfile
source "http://rubygems.org"

gem "rake"
gem "rails"
gem "i18n"
gem "rubytree", :require => "tree"
gem "coderay"
gem "fastercsv"
gem "tzinfo"
gem "net-ldap"
gem "shoulda"
gem "edavis10-object_daddy", :require => "object_daddy"
gem "mocha"
gem "mysql"
