# A sample Gemfile
source "http://rubygems.org"

gem "rake"
gem "rails", "=3.2.11"
gem "i18n", "~> 0.6.0"
gem "rubytree", :require => "tree"
gem "coderay", "~> 1.0.6"
gem "fastercsv", "~> 1.5.0"
gem "tzinfo"
gem "net-ldap", "~> 0.3.1"
gem "shoulda", "~> 2.11"
gem "edavis10-object_daddy", :require => "object_daddy"
gem "mocha", "= 0.12.3"
gem "mysql", "~> 2.8.1"
